#!/usr/bin/env bash
#install nginx on remote server
#Configure nginx to show Hello World on defautl request
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
