#!/usr/bin/env bash
#Configure nginx server to have a custom 404 page with the content Ceci n'est pas une page
apt-get -y update
apt-get -y install nginx

#FireWall settings: Allow Nginx to serve on HTTP
ufw allow 'Nginx HTTP'

#Change default home page file
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

#Redirect redirect_me page
sed -i '/server_name _;/a rewrite ^/redirect_me https://netnaija.com permanent;' /etc/nginx/sites-available/default

#Custom 404 not found page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html > /dev/null
sed -i '/server_name _;/a error_page 404 /error_404.html;' /etc/nginx/sites-available/default

#Restart nginx
service nginx restart
