#!/usr/bin/env bash
#configure a new ubuntu server

#update server packeges
apt-get -y update

#install ngix on server
apt-get -y install nginx

#allow HTTP request
ufw allow 'Nginx HTTP'

#Make default request to server display Hello World
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

#Redirect redirect_me page to another page
sed -i '/server_name _;/a rewrite ^/redirect_me https://netnaija.com permanent;' /etc/nginx/sites-available/default

#404 no page found should print Ceci n'est pas une page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html > /dev/null
sed -i '/server_name _;/a error_page 404 /error_404.html;' /etc/nginx/sites-available/default

#add header file to response header having the hostname
sed -i '/server_name _;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

#restart nginx
service nginx restart
