#!/usr/bin/env bash
#This scripts displays hours from 0-12 and minutes from 1-59

hours=0
while [ "$hours" -le "12" ]
do
	minutes="1"
	echo "Hour: " $hours
	while [ "$minutes" -le "59" ]
	do
		echo $minutes
		(("minutes += 1"))
	done
	(("hours += 1"))
done

