#!/usr/bin/env bash
# Displays:
#
#   The content of the current directory
#   In a list format
#   Where only the part of the name after the first dash is displayed (refer to the example)

content_directory=`ls`
for i in $content_directory
do
	echo $i | cut -d'-' -f2
done
