#!/usr/bin/env bash
# This script installs ufw firewall and set up few rules on a server

sudo apt-get install ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow ssh
sudo ufw allow 443
sudo ufw allow 80
sudo ufw enable
